# Generated by Django 5.2.15 on 2026-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(default=14.069444444444445, upload_to='room_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_description',
            field=models.TextField(default=14.069444444444445),
            preserve_default=False,
        ),
    ]
